spring.application.name=LAB10

# Database Configuration (Environment Variables ile beslenmeli)
# Varsayılan değer: projenin çalıştığı klasörde 'mydb.sqlite'
spring.datasource.url=${DB_URL:jdbc:sqlite:mydb.sqlite}
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logging
logging.level.org.springframework.security=INFO
